### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by Spicymang04** [Developer-Mike/Minecraft-Bedrock-Formation-Finder-1.18#2]
Programing noob here, how do you use this? Thanks.

**Comment by Developer-Mike** [comment]
It's all in README.md. Which formation do you want to find?

**Comment by Spicymang04** [comment]
Ohhhh thank you, I just need to find a 3x3x3. Seed is 1580314634219025251.

**Comment by Developer-Mike** [comment]
Command: `java -jar bedrockformation.jar 1580314634219025251 0:0 floor -1,-63,-1:1 0,-63,-1:1 1,-63,-1:1 -1,-63,0:1 0,-63,0:1 1,-63,0:1 -1,-63,1:1 0,-63,1:1 1,-63,1:1 -1,-62,-1:1 0,-62,-1:1 1,-62,-1:1 -1,-62,0:1 0,-62,0:1 1,-62,0:1 -1,-62,1:1 0,-62,1:1 1,-62,1:1`

**Comment by Spicymang04** [comment]
Thank you.
