### ISSUE TITLE
Running File

### ISSUE THREAD

**Issue by rubikgamer9** [Developer-Mike/Minecraft-Bedrock-Formation-Finder-1.18#3]
Hi, how do you run the jar file?

**Comment by Developer-Mike** [comment]
You need Java to run the jar file. The documentation and the command to run are in README.md. If you need help, please tell me which formation you want to find and I can tell you the command.

**Comment by rubikgamer9** [comment]
Thank you! I need to find a 3x3x3 bedrock cube on the overworld floor, seed is 3994304052771796313

**Comment by Developer-Mike** [comment]
Command: `java -jar bedrockformation.jar 3994304052771796313 0:0 floor -1,-63,-1:1 0,-63,-1:1 1,-63,-1:1 -1,-63,0:1 0,-63,0:1 1,-63,0:1 -1,-63,1:1 0,-63,1:1 1,-63,1:1 -1,-62,-1:1 0,-62,-1:1 1,-62,-1:1 -1,-62,0:1 0,-62,0:1 1,-62,0:1 -1,-62,1:1 0,-62,1:1 1,-62,1:1`

Result: X:-16 Z:3
