### ISSUE TITLE
Bug: BedrockBlock.shouldBeBedrock is never used

### ISSUE THREAD

**Issue by humhue** [Developer-Mike/Minecraft-Bedrock-Formation-Finder-1.18#7]
In Main.java, checkFormation is defined like this:
```
static boolean checkFormation(int x, int z) {
    for (BedrockBlock block : blocks) {
        if (!bedrockReader.isBedrock(x + block.x, block.y, z + block.z)) return false;
    }
    return true;
}
```
basically, this checks if a bedrock block is present and returns false if it's not, regardless of shouldBeBedrock.
proposed solution:
replace
`if (!bedrockReader.isBedrock(x + block.x, block.y, z + block.z)) return false;`
with
`if (block.shouldBeBedrock != bedrockReader.isBedrock(x + block.x, block.y, z + block.z)) return false;`

or perhaps a more radical change:
https://github.com/humhue/Minecraft-Bedrock-Formation-Finder-1.18/blob/e083be499578423de3d2b8069aba535e5cfd7089/src/main/java/com/mike/Main.java#L82

I'm also not sure why you sort the blocks based on their y level as it doesn't seem to affect the end result

**Comment by Developer-Mike** [comment]
You are right. Thank you for pointing this out! The sorting serves to optimize the speed. The higher the y-value, the less likely it is that the block is Bedrock, and the less likely it is that the isBedrock condition applies.
